name: ci
on: [push, pull_request]
jobs:
  busted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.4.7"
      - uses: leafo/gh-actions-luarocks@v5
      - run: luarocks install busted
      - run: busted
